Refactor and Enhance Awesome Books App
Zafron047/Awesome_Books_ES6 pull request #1
Opened 2023-06-06 18:37 UTC by Zafron047

This Pull Request refactors and enhances the Awesome Books app according to the following rules:

- [ ] Reimplemented the app using ES6 syntax for improved code readability and maintainability.

- [ ] Divided the code into modular components by creating separate files for each module in the modules directory.

- [ ] Imported the modules into the index.js file to improve code organization and separation of concerns.

- [ ] Ensured all functionalities of the app are maintained without introducing any errors during the refactoring process.

- [ ] Refactored functions to use arrow function syntax for a more concise and modern coding style.

- [ ] Utilized let and const keywords appropriately for variable declaration based on their mutability.

- [ ] Integrated the Luxon library for working with dates and times.

- [ ] Downloaded the Luxon library using npm package manager and imported it as a module.

- [ ] Implemented the display of the current date below the navigation bar using Luxon's functionalities.

- [ ] Demonstrated effective usage of a new tool (Luxon) with minimal externally curated support, simulating real-world scenarios and preparing for future professional engagements.

This Pull Request aims to improve the codebase of the Awesome Books app, enhance its functionalities, and adhere to modern JavaScript development practices.

2023-06-06 18:39 UTC, Zafron047 commented
Gratitude in advance for reviewing and contributing to the pull request. Your feedback and contributions are highly appreciated and will enhance the quality and effectiveness of the Awesome Books app. Thank you for your support!

Best regards,

Nohain Islam Zafron 😄

2023-06-06 18:53 UTC, binhussen requested changes
Hi @Zafron047 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- Well Stractured Code✔️
- Sticked Given WIreframe ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +  }
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-06 18:53 UTC, binhussen commented on modules/bookshelf.js
> +}
- Great job for implementing using class, I think in this milestone you have to use an arrow function to fit the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md) 👍 
<img width="524" alt="Screenshot 2023-06-05 154539" src="https://github.com/AnsarIbrahim/Awesome-books-with-ES6/assets/52010789/d7ae5a67-d7ea-41f7-a937-071869c1036b">

2023-06-07 05:51 UTC, Zafron047 commented
Hello @binhussen, 

Thank you for pointing out the issue. I have made the necessary changes to the code by converting all the regular functions inside the class to Arrow functions. This should address the concern you raised.

Best regards,
[Your Name]

2023-06-07 06:05 UTC, wayungi approved these changes
Hi @Zafron047 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Arrow functions used ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 07:35 UTC, Zafron047 commented
@wayungi Thanks a lot for giving your time to review it.
Have a great day. 👍 😄

2023-06-07 07:35 UTC, merged